### ISSUE TITLE
Thank you very much for program

### ISSUE THREAD

**Issue by mrkaban** [WaGi-Coding/WaGis-Mass-IP-Blacklister-Windows#13]
Thank you very much for the program with a free open source license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%B1%D0%B5%D0%B7%D0%BE%D0%BF%D0%B0%D1%81%D0%BD%D0%BE%D1%81%D1%82%D1%8C/%D1%81%D0%B5%D1%82%D0%B5%D0%B2%D1%8B%D0%B5-%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D1%8B/wagis-ip-block.html).

Please do not drop the project, the program is very interesting!

How about translating the interface into other languages? ready to help with translation into Russian

**Comment by WaGi-Coding** [comment]
Hey, thanks for sharing the Tool. I don't think i'll work much more on it, anyway it should work pretty good in most cases.

I don't see the need for a translation, as it's a really simple UI with easy words to understand.
