### ISSUE TITLE
Run as Service

### ISSUE THREAD

**Issue by Justice81** [WaGi-Coding/WaGis-Mass-IP-Blacklister-Windows#2]
Is there a way to start ist as service?

Thank you

**Comment by WaGi-Coding** [comment]
I am sorry to tell you it's not possible. May add this to my To-Do list.

Greetings from Vienna and thanks for the idea. Have a great day :)

Am Mo., 6. Mai 2019 um 16:01 Uhr schrieb Justice81 <notifications@github.com

**Comment by WaGi-Coding** [comment]
I am sorry to tell you it's not possible. May add this to my To-Do list.

Greetings from Vienna and thanks for the idea. Have a great day :)
