### ISSUE TITLE
WIndows Server 2008 R2

### ISSUE THREAD

**Issue by abucoict** [WaGi-Coding/WaGis-Mass-IP-Blacklister-Windows#3]
Hello, Windows Server 2008 R2 has unfortunately same limit (1000 lines) as Windows 7 , is it possible to update it? 

Thank you

**Comment by reketeee** [comment]
If you run the app in compatibility mode with windows 7 as administrator, works fine with W2K8R2

**Comment by abucoict** [comment]
Thank you, it helped.

**Comment by WaGi-Coding** [comment]
thanks for helping

I'll maybe update it soon. Just working on some other project currently.

**Comment by WaGi-Coding** [comment]
The latest 1.3.6 update should fix it. Would be great if you can tell me it's true :)

**Comment by abucoict** [comment]
New version fixed it. Thank you

**Comment by WaGi-Coding** [comment]
Thanks for testing, have a great day.
